# Generated by Django 4.0 on 2021-12-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default='hello', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
