# Generated by Django 4.0 on 2021-12-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10, verbose_name='Discount'),
            preserve_default=False,
        ),
    ]
