# Generated by Django 4.0 on 2021-12-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_package_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default='', upload_to='packages', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
