# Generated by Django 4.0 on 2022-01-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_shift_employee_shift_name_timing_shift'),
        ('core', '0008_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', verbose_name='Employee'),
            preserve_default=False,
        ),
    ]
