# Generated by Django 4.0 on 2022-01-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_shift_employee_shift_name_timing_shift'),
        ('core', '0011_alter_appointment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.employee', verbose_name='Employee'),
        ),
    ]
