# Generated by Django 4.0 on 2022-01-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_holiday_shifts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shifts',
            new_name='Shift',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
    ]
