# Generated by Django 4.0 on 2022-01-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_created',
        ),
    ]
