# Generated by Django 4.0 on 2022-01-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.AddField(
            model_name='shift',
            name='name',
            field=models.CharField(default='Morning Shift', max_length=100),
        ),
        migrations.AddField(
            model_name='timing',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.shift'),
        ),
    ]
