# Generated by Django 4.0.3 on 2022-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_employee_id_alter_holiday_id_alter_shift_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='holiday_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
