# Generated by Django 4.0.3 on 2022-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_holiday_date_holiday_date_holiday_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
