# Generated by Django 4.0.3 on 2022-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_holiday_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='holiday_pictures'),
        ),
    ]
