# Generated by Django 4.0.3 on 2022-06-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_holiday_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.TextField(),
        ),
    ]
