# Generated by Django 4.0.3 on 2022-06-25 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_holiday_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Holiday', to=settings.AUTH_USER_MODEL),
        ),
    ]
