# Generated by Django 4.0.3 on 2022-07-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_holiday_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='accepted',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Accepted', max_length=100, null=True),
        ),
    ]
