# Generated by Django 4.0.3 on 2022-07-02 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_holiday_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
